
const ACTIONS = {
  FETCH_CONTACT_STARTED: `FETCH_CONTACT_STARTED`,
  FETCH_CONTACT_ERROR: `FETCH_CONTACT_ERROR`,
  FETCH_CONTACT_SUCCESS: `FETCH_CONTACT_SUCCESS`,
  FETCH_US_CONTACT_STARTED: `FETCH_US_CONTACT_STARTED`,
  FETCH_US_CONTACT_ERROR: `FETCH_US_CONTACT_ERROR`,
  FETCH_US_CONTACT_SUCCESS: `FETCH_US_CONTACT_SUCCESS`,
};

export default ACTIONS;
